import Image from "next/image";
import IMAGE_SIZES from "@/content/image-sizes.json";

const SIZES = IMAGE_SIZES as unknown as Record<string, [number, number]>;

type Props = {
  images: string[];
  alt: string;
  badge?: string;
};

/**
 * Continuous product gallery — every photo stacked vertically, each at
 * its own natural aspect ratio so portrait pieces (e.g. 1920×2880) and
 * landscape shots (e.g. 1920×1280) both render edge-to-edge with no
 * crop, stretch, or letterbox bands.
 *
 * The real width/height of every /products/ image is read at build time
 * into image-sizes.json (generated by scripts; ~161 entries). We pass the
 * true dimensions to next/image so it reserves the correct box and CSS
 * `w-full h-auto` lets the column take each image's own ratio. The old
 * code hard-coded 1920×2880 for every shot, which forced the 100+
 * landscape photos into a tall 2:3 box and distorted/cropped them — this
 * fixes that. Falls back to 3:2 (the catalogue majority) for any image
 * missing from the manifest.
 */
export function ProductGallery({ images, alt, badge }: Props) {
  const shots = images.length > 0 ? images : [];

  return (
    <div className="flex flex-col gap-1 md:gap-2">
      {shots.map((src, i) => {
        const [w, h] = SIZES[src] ?? [1600, 1067];
        return (
        <div
          key={`${src}-${i}`}
          className="relative w-full overflow-hidden"
        >
          <Image
            src={src}
            alt={i === 0 ? alt : `${alt} — ${i + 1}`}
            width={w}
            height={h}
            priority={i === 0}
            sizes="(min-width: 1024px) 56vw, 100vw"
            className="block w-full h-auto"
          />
          {badge && i === 0 && (
            <span className="absolute top-5 left-5 z-10 inline-flex items-center gap-2 bg-foreground text-background px-3 py-1.5 text-[10px] tracking-[0.32em] uppercase">
              {badge}
            </span>
          )}
        </div>
        );
      })}
    </div>
  );
}